config/routes.rb
Rails.application.routes.draw do
  get '/main', action: 'main', controller: 'titles'
  get '/create', action: 'create', controller: 'titles'
  get 'titles/entryadd', action: 'entryadd', controller: 'titles'
  get 'titles/entrydelete', action: 'entrydelete', controller: 'titles'
  root 'sessions#index'
  get '/index', action: 'index', controller: 'sessions'
  resources :users
  resources :titles
  resources :entry_path
  get '/sign_up', action: 'sign_up', controller: 'sessions'
  post '/auth', action: 'auth', controller: 'sessions'
  get '/log_out', action: 'logout', controller: 'sessions'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
end

app/models/lastentry.rb
class Lastentry < ApplicationRecord
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  validates_uniqueness_of :name
  validates_length_of :name, minimum: 3
  validates_length_of :password, minimum: 3


  def authenticate(taken_pass)
    password == taken_pass
  end

  def admin?
    admin
  end
end

app/controllers/application_controller.rb
require 'turbolinks'
class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || session[:locale] || I18n.default_locale
    session[:locale] = I18n.locale
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  require "digest"

  def index
    redirect_to controller: 'titles', action: 'main' if current_user
  end

  def auth
    user = User.find_by_name(params[:name])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, alert: 'Authenticated'
    else
      redirect_to root_path, alert: 'Password/Login are incorrect'
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to root_path, alert: 'Logged Out'
  end
end

def encrypt_md5(text)
  Digest::MD5.hexdigest text
end

app/controllers/titles_controller.rb
class TitlesController < ApplicationController
  before_action :set_entry, only: :show

  def main
    @database = Entry.all
    @dbcount = 0
  end

  def create
    redirect_to root_path, flash: { alert: 'Sign in first!' } unless current_user&.admin
    if params[:entryname] and params[:genretype] and params[:entrydate] and params[:entrysynopsis] and params[:entrytags] and params[:entryposter]
      ename = params[:entryname].delete(',', '"', "'", ';')
      egenre = params[:genretype].delete(',', '"', "'", ';')
      edate = params[:entrydate].delete(',', '"', "'", ';')
      esyn = params[:entrysynopsis].delete(',', '"', "'", ';')
      etags = params[:entrytags].delete(',', '"', "'", ';')
      epos = params[:entryposter].delete(',', '"', "'", ';')
      Entry.create name: ename, genre: egenre, date: edate, synopsis: esyn, tags: etags, poster: epos
    end
  end

  def entryadd
    if Profile.find_by_username(current_user[:name]) == nil
      Profile.create username: current_user[:name], entries: ''
    end
    pentries = Profile.find_by_username(current_user[:name])
    curentries = pentries[:entries]. + ' ' + Lastentry.last[:entryid]
    pentries.update_attribute(:entries, curentries)
    Lastentry.destroy_all
    redirect_to root_path
  end

  def entrydelete
    pentries = Profile.find_by_username(current_user[:name])
    curentries = pentries[:entries]
    currs = curentries.gsub! Lastentry.last[:entryid], ' '
    pentries.update_attribute(:entries, currs)
    Lastentry.destroy_all
    redirect_to root_path
  end

  def set_entry
    @title = Entry.find(params[:id])
  end

  def show
    @title = Entry.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    redirect_to root_path, flash: { alert: 'Sign in first!' } unless current_user
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    redirect_to root_path, flash: { alert: 'Sign in first!' } unless current_user
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    redirect_to root_path, flash: { alert: 'Sign in first!' } unless current_user && current_user.admin?
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, alert: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
    Profile.find_by_username(@user.name).destroy
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :password, :admin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_path(params={})
    url_for(request.params.merge(params))
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/titles_helper.rb
module TitlesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Too Many Entries</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body class="site-theme-dark site-dark-text">
<header>
  <nav class='navbar fixed-top navbar-expand-lg navbar-dark bg-dark'>
    <div class="navbar-brand"><%= image_tag("tmesmall.png", size: '80x40') %></div>
    <div class="site-dark-text"><%= link_to(t('.main'), { controller: 'titles', action: 'main' }, class: 'nav-link apptext') %></div>

    <% if current_user&.admin %>
      <div class="site-dark-text"><%= link_to(t('.add'), '/create', class: 'nav-link apptext') %></div>
    <% end %>

    <% if current_user %>
      <div class="site-dark-text"><%= link_to(t('.users'), { controller: 'users', action: 'index' }, class: 'nav-link apptext') %></div>
    <% end %>
    <div class="nav-item">
      <%= link_to t('Ru'), current_path(locale: 'ru'), class: 'nav-link apptext' %>
    </div>
    <div class="nav-item">
      <%= link_to t('En'), current_path(locale: 'en'), class: 'nav-link apptext' %>
    </div>
    <% if current_user %>
      <div class="container-fluid">
      </div>
      <span class="notices side-dark-text"><%= t('.hello') %><%= current_user.name %>!</span>
      <div class="navbar-nav site-dark-text"><%= link_to(t('.logout'), { controller: 'sessions', action: 'logout' }, class: 'btn btn-outline-light') %></div>
    <% else %>
      <div class="container-fluid">
      </div>
      <span class="navbar-text notices"><%= t('.urenot') %></span>
      <div class="navbar-nav"><%= link_to(t('.login'), { controller: 'sessions', action: 'index' }, class: 'btn btn-outline-light') %></div>
    <%end %>
  </nav>
</header>

<%= yield %>
</body>
</html>

app/views/titles/create.html.erb
<br/><br/><br/>
<div class="row justify-content-center text-center">
  <h1 class="col-12 head"><%= t('.header') %></h1>
  <%= form_tag url_for(controller: 'titles', action: 'create'), method: 'get' do %>
<br/>
    <%= label_tag t('.name') %>
    <%= text_field_tag :entryname %>
    <br><br/>
    <%= label_tag t('.genre') %>
    <%= text_field_tag :genretype %>
    <br/><br/>
    <%= label_tag t('.release') %>
    <%= text_field_tag :entrydate %>
    <br/><br/>
    <%= label_tag t('.synopsis') %>
    <%= text_area_tag :entrysynopsis, nil, size: '80' %>
    <br/><br/>
    <%= label_tag t('.tags') %>
    <%= text_field_tag :entrytags %>
    <br/><br/>
    <%= label_tag t('.poster') %>
    <%= text_field_tag :entryposter %>
    <br/><br/>
    <%= submit_tag t('.add') %>
  <% end %>
</div>

app/views/titles/main.html.erb
<div id="carouselExampleSlidesOnly" class="carousel slide pupa text-center" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag 'slide1.jpg', class: 'd-block w-120', alt: 'First slide', width: '1300'; %>
    </div>
    <div class="carousel-item">
      <%= image_tag 'slide2.jpg', class: 'd-block w-120', alt: 'Second slide', width: '1300' %>
    </div>
    <div class="carousel-item">
      <%= image_tag 'slide3.jpg', class: 'd-block w-120', alt: 'Third slide', width: '1300' %>
    </div>
    <div class="carousel-item">
      <%= image_tag 'slide4.jpg', class: 'd-block w-120', alt: 'Fourth slide', width: '1300' %>
    </div>
    <div class="carousel-item">
      <%= image_tag 'slide5.jpg', class: 'd-block w-120', alt: 'Fifth slide', width: '1300' %>
    </div>
    <div class="carousel-item">
      <%= image_tag 'slide6.jpg', class: 'd-block w-120', alt: 'Sixth slide', width: '1300' %>
    </div>
  </div>
</div>
<div class="container">

  <div class="col-12 head text-center otstup"><%= image_tag("tme.png") %></div>
<br/><br/>
  <div class="mainheader otstup"><h1 class="text-center row entryheader"><%= t('.header') %></h1></div>
  <br/><br/>
  <div class="row">
    <% @database.each do |entry| %>
    <div class="col-3">
      <div class="entrypic">
        <img src = <%= entry[:poster] %> width="250" height="370" />
        <div class="entrypicex text-center"><%= link_to t('.show'), titles_path + '/' + entry[:id].to_s, class: "apptext" %></div>
        <div><% @dbcount += 1 %></div>
      </div>
    </div>
    <% if @dbcount%4==0 %>
      </div>
      <div class="row toppls">
    <% end %>
    <% end %>
  </div>
</div>
<br/><br/>

app/views/titles/show.html.erb
<br/><br/><br/>
<br/>
<div class="container">
  <div class="row entryshow">
    <div class="col-3 text-center">
      <img src = <%= @title[:poster] %> width="250" height="370" alt = <%= @title[:id] %> />
    </div>
    <div class="col-9 mainheader">
      <h1 class = "entryheader"><%= @title[:name] %></h1>
      <br/>
      <div><span class="topics"><%= t('.genre') %></span> <%= @title[:genre] %></div>
      <br/>
      <div><span class="topics"><%= t('.date') %></span><%= @title[:date] %></div>
      <br/>
      <div><span class="topics"><%= t('.tags') %></span><%= @title[:tags] %></div>
      <br/>
      <div><span class="topics"><%= t('.discription') %></span> <%= @title[:synopsis] %></div>
    </div>
    <div class="row">
      <div>
        <% if current_user %>
          <% Lastentry.create entryid: @title[:id].to_s %>
          <% if Profile.find_by_username(current_user[:name]) %>
            <% if Profile.find_by_username(current_user[:name])[:entries].split(' ').index(Lastentry.last[:entryid]) %>
              <%= link_to(t('.delete'), { controller: 'titles', action: 'entrydelete' }, class: 'btn btn-danger somebutton') %>
              <% else %>
              <%= link_to(t('.add'), { controller: 'titles', action: 'entryadd' }, class: 'btn btn-primary somebutton') %>
            <% end %>
          <% else %>
            <%= link_to(t('.add'), { controller: 'titles', action: 'entryadd' }, class: 'btn btn-primary somebutton') %>
          <% end %>
        <% end %>
        <%= link_to(t('.back'), :back, class: 'btn btn-primary somebuttont') %>
      </div>
    </div>
  </div>
  <br/><br/><br/>
  <div class="row">
    <% if !current_user %>
      <h1 class = "col-12 text-center"><%= link_to(t('.login'), { controller: 'sessions', action: 'index' }, class: 'login') %><%= t('.toadd') %></h1>
    <% end %>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %><%= t('.proh') %></h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label t('.name') %>
    <%= form.text_field :name, class: 'form-control' %>
    <br/>
  </div>

  <div class="field">
    <%= form.label t('.password') %>
    <%= form.password_field :password, class: 'form-control' %>
  </div>

  <% if current_user&.admin? %>
    <div class="field">
      <%= form.label :admin %>
      <%= form.check_box :admin %>
    </div>
  <% end %>

  <br />

  <div class="actions">
    <%= form.submit(t('.submit'), class: 'btn btn-primary') %>
  </div>

<% end %>

app/views/users/edit.html.erb
<br/><br/><br/>
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to t('.show'), @user %> |
<%= link_to t('.back'), users_path %>

app/views/users/index.html.erb
<br/><br/><p id="notice"><%= notice %></p>
<div class = 'modif'>
  <h1>Users</h1>

  <table>
    <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @users.each do |user| %>
      <tr class="row entryshow toppls">
        <td class="usershow col-4"><%= user.name %></td>
        <td class="useradmin col-4"><%= t('.admin') if user.admin %></td>
        <td class="apptext"><%= link_to t('.show'), user, class: "apptext" %></td>
        <% if current_user&.admin? %>
          <td class = "col-4 apptext otstup"><%= link_to t('.edit'), edit_user_path(user), class: "apptext" %></td>
          <% if !user.admin %><td class="col-4 otstup"><%= link_to t('.destroy'), user, method: :delete, data: { confirm: t('.confirm') }, class: "deltext" %></td><% end %>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<div class="text-center row justify-content-center">
  <% session[:user_id] = nil %>
  <h1 class="col-12 mod">New User</h1>

  <%= render 'form', user: @user %>

  <div class="col-12"></div>
  <%= link_to(t('.back'), { controller: 'sessions', action: 'index' }, class: 'btn btn-outline-primary') %>

</div>

app/views/users/show.html.erb
<br/><div class="modif">
  <p id="notice"><%= notice %></p>
  <br/>
  <p class="usershow usershow">
    <strong>Name:</strong>
    <%= @user.name %>
  </p>
  <br/><br/><br/>


  <div class="container">
      <% if Profile.find_by_username(@user.name) and Entry.find_by_id(Profile.find_by_username(@user.name)[:entries])%>
      <div><h1 class="text-center">Watched list:</h1></div>
      <% Profile.find_by_username(@user.name)[:entries].split(' ').each do |entry| %>
        <div class="row userlist entryshow">
          <div class="col-2">
            <img src = <%= Entry.find_by_id(entry)[:poster] %> width="125" height="185" class/>
          </div>
          <div class="col-10">

            <h3 class="entryheader"><%= link_to Entry.find_by_id(entry)[:name], titles_path + '/' + entry, class: "apptext" %></h3><br/>
            <div><span class="topics"><%= t('.genre') %></span><%= Entry.find_by_id(entry)[:genre] %></div><br/>
            <div><span class="topics"><%= t('.date') %></span><%= Entry.find_by_id(entry)[:date] %></div><br/>
            <div><span class="topics"><%= t('.tags') %></span><%= Entry.find_by_id(entry)[:tags] %></div>
          </div>
        </div>
      <% end %>
      <% else %>
        <h1 class="text-center"><%= t('.nothing') %></h1>
      <% end %>
  </div>
  <br/><br/>
  <% if current_user&.admin? %><%= link_to t('.edit'), edit_user_path(@user), class: "usershow" %> | <% end %>
  <%= link_to t('.back'), users_path, class: "apptext" %>
</div>